### ISSUE TITLE
Can't inject dependency - it is undefined

### ISSUE THREAD

**Issue by Invis1ble** [hboylan/ng2-http#1]
Hi. I'm trying to inject some dependency to the service that extends `RESTClient`, but seems it doesn't work:
```ts
@Injectable()
@BaseUrl('...')
@DefaultHeaders({
    // ...
})
export class JwtService extends RESTClient {

    constructor(
        http: Http,
        @Inject(CONFIG) private config: Config
    ) {
        super(http);

        console.log(this.config); // undefined
    }

    // ...

}
```

**Comment by hboylan** [comment]
@Invis1ble Thanks for trying out the new module. Looks like a typo to me.

`@Inject(CONFIG)` uses all caps, but the class appears to be spelled `Config`.
Also, make sure the `@BaseUrl('...')` contains a real app domain instead of "..."

**Comment by Invis1ble** [comment]
@hboylan

> `@Inject(CONFIG)` uses all caps, but the class appears to be spelled `Config`

`CONFIG` is an [`OpaqueToken`](https://angular.io/docs/ts/latest/guide/dependency-injection.html#!#opaquetoken). The same injection works fine in other services.
Also if I remove extending, then I get the right Object, so injection works:

``` ts
@Injectable()
// @BaseUrl('...')
// @DefaultHeaders({
//     // ...
// })
export class JwtService {

    constructor(
        http: Http,
        @Inject(CONFIG) private config: Config
    ) {
        // super(http);

        console.log(this.config); // Object {...}
    }

    // ...

}
```

> make sure the @BaseUrl('...') contains a real app domain instead of "..."

Yes, it contains valid URL. I simply removed insignificant details.

**Comment by hboylan** [comment]
Hmm, I've never had to use an OpaqueToken before, but I can't seem to get `@Inject()` working for regular classes either.

**Comment by Invis1ble** [comment]
Forget about `OpaqueToken`, I can't inject a regular injectable services too :)

``` ts
@Injectable()
export class FooService {}
```

``` ts
@Injectable()
export class JwtService {

    constructor(
        private fooService: FooService
    ) {
        console.log(this.fooService); // FooService {}
    }

    // ...

}
```

``` ts
@Injectable()
@BaseUrl('http://domain.com')
export class JwtService extends RESTClient {

    constructor(
        http: Http,
        private fooService: FooService
    ) {
        super(http);

        console.log(this.fooService); // undefined
    }

    // ...

}
```

**Comment by hboylan** [comment]
[This](http://blog.thoughtram.io/angular/2016/05/23/opaque-tokens-in-angular-2.html#opaque-tokens-to-the-resque) explained OpaqueTokens. It _does_ inject into a class using the custom decorators.

My guess is that you aren't properly "providing" the dependencies you're trying to inject.

``` typescript
// app.config.ts
export class Config {
  public api: string = "http://localhost:3000"
}

export let CONFIG = new OpaqueToken('app.config')
```

``` typescript
// app.module.ts
@NgModule({
  providers: [Service, { provide: CONFIG, useClass: Config }]
})
export class AppModule {}
```

``` typescript
//app.service.ts
@Injectable()
@BaseUrl(...)
@DefaultHeaders(...)
export class Service extends RESTClient {

  constructor(
    protected http: Http,
    @Inject(CONFIG) private config: Config
  ) {
    super(http)
    console.log(config) // {api: "http://localhost:3000"}
  }
}
```

**Comment by Invis1ble** [comment]
The problem is not in injecting config. I know how to provide dependecies with `NgModule.providers`. Please have a look at my comment above. This issue also appears with any injectable service and only when I extending `RESTClient`. Also I've created a simple [plunk](https://plnkr.co/edit/bkAK88mvzpmGVeelDSKT?p=info) and it works fine. Seems like the issue appears on `angular-cli` project. I'll try to debug my code later.
