### ISSUE TITLE
No way to inject dependencies

### ISSUE THREAD

**Issue by b264** [hboylan/ng2-http#10]
The call to super
```
  constructor(protected http: Http, private thing: Thing) {
    super(http)
  }
```
precludes any dependency injection of `thing`.  So while you can certainly `consume` a REST service, you cannot store anything (such as the logged-in user id) anywhere.  So as soon as user navigates to another page, you have no idea who they are any more because you cannot inject a dependency in order to store any data.  example: `thing.userId = 5;`

**Comment by Schwoebel** [comment]
Hi, 
There is a way to do this with some extra pieces of code.

You have to crate a service provider and add it to your module. 

I did something like this:


    import { UserService } from './src/modules/SharedModule/services/user.service';
    import { Http } from '@angular/http';
    import { UserStorage } from './src/modules/SharedModule/storage/user.storage';

    let userServiceFactory = (http: Http, userStorage: UserStorage) => {
      return new UserService(http, userStorage);
    };

    export let userServiceProvider =
    { provide: UserService,
    useFactory: userServiceFactory,
        deps: [Http, UserStorage]
    };

So in your case it would be:

    let userServiceFactory = (http: Http, thing: Thing) => {
    return new UserService(http, thing);
    };

    export let userServiceProvider =
    { provide: UserService,
     useFactory: userServiceFactory,
    deps: [Http, Thing]
    };
    
Then you would add that to your module so it provides your special version of the service to your app.

Another way around it, that I used first, was to create a "thing" variable in the service class and then set it in your class constructor.  Not optimal, but it worked.

It took me a while to figure out how to do it, but I eventually figured it out with trial and error after reading this part of the Angular2 docs: https://angular.io/docs/ts/latest/guide/dependency-injection.html#!#factory-providers

If you have actually done this already, and are just looking for a way to store thing.id=5 without doing it outside of the service class, you can use the request interceptor that comes with this package oob:

    protected responseInterceptor(res: Observable<Response>): Observable<Response> {
        ::code that sets thing.id::
        return res
    }

**Comment by hboylan** [comment]
Another solution, which I'm using, is to preclude the dependency injection within a parent class.
Hope this helps!

```typescript
// parent service
export class APIService extends RESTClient {

  constructor(
    protected http: Http,
    protected router: Router,
    protected localStorage: LocalStorageService
  ) { super(http) }

  // root interceptors
}

// child service
export class CustomerService extends APIService {

  constructor(
    protected http: Http,
    protected router: Router,
    protected localStorage: LocalStorageService
  ) { super(http, router, localStorage) }

  // methods
}
```

I welcome any other solutions to this as well as PRs ;)

**Comment by b264** [comment]
@hboylan That looks fantastic!  Unfortunately, it demonstrates exactly the same behaviour.  Are there any small details that were left out?

**Comment by Schwoebel** [comment]
Look at what I wrote @b264

**Comment by hboylan** [comment]
Ah, now I see what @b264 is suggesting. The link he provided is very helpful, but to summarize...

```typescript
// user.service - add custom service provider via factory method
let userServiceFactory = (http: Http, thing: Thing) => {
  return new UserService(http, thing)
}

export let userServiceProvider = {
  provide: UserService,
  useFactory: userServiceFactory,
  deps: [Http, Thing]
}

// user.component - use custom service provider to inject UserService
import { userServiceProvider } from './user.service'
@Component({
  ...
  providers: [userServiceProvider]
})
export class UserComponent {
  constructor(private userService: UserService) { }
}
```

**Comment by b264** [comment]
This is still unresolved

**Comment by hboylan** [comment]
@b264 There are a couple of options for dependency injection outlined above.
- Class inheritance
- Angular providers

Do either of these work for you?
Do you have another suggestion?

**Comment by b264** [comment]
Class inheritance and providers both worked, but only when I copy/pasted the code into my project.  Requiring it per the directions fails every single time.  I figured out that `rest.service.ts` and `util.ts` work GREAT if I copy them into my project.  I don't like doing this, I prefer bower or npm.  `rest.module.ts` is what breaks everything.

**Comment by b264** [comment]
See https://github.com/hboylan/ng2-http/pull/15

**Comment by b264** [comment]
The first answer above by @hboylan is very similar to what works -- as long as I don't use `rest.module.ts`

**Comment by b264** [comment]
I'm not sure, but I think this line https://github.com/hboylan/ng2-http/blob/28d7060d2550c17bc4a66873d12a150540be9f8e/src/rest.module.ts#L14 causes the dependencies to be injected with different instances.  So I can inject an instance of `Thing` and I can inject an instance of `Thing` elsewhere, but instead of a singleton, it's two sepearate instances, which makes it completely useless for storing state.  Effectively, importing this as per the directions makes it stateless.  Effectively.  Because it all has state, but those states are uncoupled and not available from any other service.

**Comment by hboylan** [comment]
@b264 Make sure you're importing `RESTModule` into your app properly.

Here's an example of the base `api.module.ts` I use across projects:
```typescript
// api.module
import {NgModule} from '@angular/core'
import {RESTModule} from 'ng2-http'
import {ApiService} from './api.service'
import {UserService} from './user.service'

@NgModule({
  imports: [RESTModule],
  providers: [
    ApiService,
    UserService
  ]
})
export class ApiModule {}
```
```typescript
// api.service
import {Injectable} from '@angular/core'
import {Http} from '@angular/http'
import {RESTClient, BaseUrl, DefaultHeaders} from 'ng2-http'

@Injectable()
@BaseUrl('http://localhost:3000')
@DefaultHeaders({
  'Accept': 'application/json',
  'Content-Type': 'application/json'
})
export class ApiService extends RESTClient {
  constructor(protected http: Http) { super(http) }
}
```
```typescript
// user.service
import {Injectable} from '@angular/core'
import {Http} from '@angular/http'
import {GET, POST, Path, Body, Produces} from 'ng2-http'
import {Observable} from 'rxjs/Observable'
import {ApiService} from './api.service'

@Injectable()
export class UserService extends ApiService {

  constructor(protected http: Http) {super(http)}

  @POST('/users')
  @Produces<User[]>()
  search(@Body pagination: Pagination): Observable<User[]> {
    return null;
  }

  @GET('/users/{_id}')
  @Produces<User>()
  find(@Path('_id') _id: string): Observable<User> {
    return null;
  }
}
```

**Comment by hboylan** [comment]
Maybe you're trying to preserve too much state within your child REST service. Their methods behave abstractly

**Comment by b264** [comment]
I don't need to preserve any state at all, except for the provider whose responsibility it is to remember the logged-in userID or authToken.  Without this, an API service is useless. This provider, or singleton, ends up with a separate instance when doing it this way.  One instance while inside RESTClient, and a separate one in everything else.  I don't understand how you can not have this problem, or how anyone can use this without this being solved.  I spent days and days on this and even hired help-- before concluding the library was broken-- specifically `rest.module.ts`  I was importing it exactly as described.  I do have more imports than that, though, including:
```
  imports: [
    HttpModule,
    BrowserModule,
    AgmCoreModule.forRoot({
      apiKey: Project.googleMapsApiKey,
    }),
    IonicModule.forRoot(AppComponent, {
      locationStrategy: 'hash',
      swipeBackEnabled: true,
      tabsPlacement: 'bottom',
      platforms: {
        md: {
        },
        ios: {
          tabsPlacement: 'bottom',
        },
        wp: {
        },
      },
    }, deepLinkConfig),
    IonicStorageModule.forRoot(),
  ],
```

The only common theme here, despite thousands of combinations tried, is that any time `rest.module.ts` is involved, it does not work, and anytime it isn't involved, it does work.  Every. Single. Time.

Do you have any idea what can cause this?

**Comment by b264** [comment]
To be clear, `rest.service.ts` and `util.ts` work perfectly :-D

**Comment by b264** [comment]
@hboylan Do you have an example import that is working?  I'd like to switch back to the library if possible.

**Comment by hboylan** [comment]
Check the demo project in source.

**Comment by b264** [comment]
The demo project in source does not store state.  For example, a logged-in user id that was obtained from the API.
