### ISSUE TITLE
Perform async operation within request interceptor

### ISSUE THREAD

**Issue by daibertdiego** [hboylan/ng2-http#11]
I use the library ng2-http and i'm trying get the CSRF Token from my backend and put him on my request before that is executed.
The code of generic service is like this:

```typescript
import { Injectable } from '@angular/core';
//import {Http, Headers} from '@angular/http';
import { Http, Response, RequestOptions, Request, RequestMethod } from '@angular/http';
import { Observable } from 'rxjs/Rx';

import { RESTClient } from 'ng2-http';


@Injectable()
export class GATRest extends RESTClient {

  token: string;
  csrf: string;

  constructor(protected http: Http) {
    super(http);
  }

  protected requestInterceptor(req: Request): Request {
    console.log("REQUEST GATRest");
    console.log(req);
    // set token if saved in local storage
    var currentUser = JSON.parse(localStorage.getItem('currentUser'));
    this.token = currentUser.token;

    req.headers.append('Authorization', 'Bearer ' + this.token);
    req.withCredentials = true;
    if (req.method != 0) {
      this.getCSRFToken(req).subscribe(
        (res) => {
          this.csrf = res;
          console.log("Valor do CSRF retornado " + this.csrf);
          req.headers.append('Set-Cookie', 'XSRF-TOKEN=' + this.csrf);
          req.headers.append('X-XSRF-TOKEN', this.csrf);
          console.log("Valor do Cookie da requisição " + req.headers.get("Set-Cookie"));
          console.log("Valor do Header da requisição " + req.headers.get("X-XSRF-TOKEN"));
          console.log("Vai retornar o Request" + Date.now());
          console.log(req);
          return req;
        });
      console.log("RETORNOU O REQUEST ANTES DO CSRF CHEGAR!!!");
      return req;
    } else {
      return req;
    }
    //console.log("RETORNOU O REQUEST ANTES DO CSRF CHEGAR!!!");
  }

  protected responseInterceptor(res: Observable<Response>): Observable<Response> {
    console.log("RESPONSE GATRest");
    console.log(res);
    return res;
  }

  getCSRFToken(req: Request): Observable<string> {
    console.log("Requisitar CSRF TOKEN");
    return this.http.get("http://localhost:8080/csrf", {
      headers: req.headers
    }).map((res) => res.text());
  }
}
```

How i return de request for the ng2-http always after get the CSRF token from backend? Thank You

**Comment by hboylan** [comment]
The request interceptor is meant to manipulate the request, but not actually perform it. Try setting the headers you need without performing the GET.

```typescript
protected requestInterceptor(req: Request): Request {
  var currentUser = JSON.parse(localStorage.getItem('currentUser'))
  if (req.method != 0) {
    req.headers.set('Authorization' `Bearer ${currentUser.token}`)
  }
  return req
}
```

**Comment by hboylan** [comment]
Important to note that you should edit the server code to verify tokens with each request. If token needs refreshed, do that in same request as well.

**Comment by daibertdiego** [comment]
Thank you for the fast reply. The only problem is that csrf token from backend is generated dynamically. And i need perform the get all times before a Post, Put or Delete.

**Comment by hboylan** [comment]
Hmm... well if you can't return a token with each prior request, then you probably need the request interceptor to look like the following, correct?

```typescript
protected requestInterceptor(req: Request): Observable<Request>
```

**Comment by daibertdiego** [comment]
Exactly, i need to modify the header of request with a result of another request (GET of CSRF Token) every time than the request is a POST, PUT or DELETE.

**Comment by hboylan** [comment]
Working on this... Want to be sure that the request interceptor is able to handle both sync and async interceptions easily.

Could be annoying to have to also import ```Observable.of()``` just to wrap a normal ```Request```.

```typescript
import {Request} from '@angular/http'
import {Observable} from 'rxjs/Observable'
import 'rxjs/add/observable/of'
...
protected requestInterceptor(req: Request): Observable<Request> {
  return Observable.of(req)
}
```

**Comment by daibertdiego** [comment]
Oh nice. I didn't know about this Observable.of(). Now, i disabled temporarily the CSRF on backend to continue developing the front-end with your api. And has been amazing. Congratulations by this work. And i will wait for the new releases. Cheers

**Comment by iagocanalejas** [comment]
Quite anoying behaviour for a backend, your token shouldn't be refreshed each request. 

Maybe your logic should be moved to a retry feature raised if response code is unauthorized? Something like [Retroauth](https://github.com/andretietz/retroauth/tree/master/retroauth-android) does with retrofit in android (think this lib is based on it)??

I will give a try implementing this, need it too for my app.

**Comment by iagocanalejas** [comment]
Thought in something like this but can't found a way of creating a new request. Maybe pass it to `responseInterceptor()` so you can clone it?

```javascript
  protected responseInterceptor(res: Observable<Response>): Observable<Response> {
    return res.catch(error => {
      if (error.status === 401) {
        let token: Token = Token.load();
        this.login(User.buildLoginParams(token.username, token.refresh_token))
          .mergeMap((data: Token) => {
            Token.save(data, token.username);
            // TODO return new res
            return null;
          })
          .catch(() => {
            Token.remove();
            return Observable.fromPromise(this.router.navigate(["login"]));
          });
      }
      return Observable.throw(error);
    });
  }

  @POST('auth/login/' + CLIENT)
  @Headers({
    'Content-Type': 'application/x-www-form-urlencoded',
    'Accept': 'application/json; version=1.0'
  })
  @Produces<Token>()
  public login(@Body authBody: string): Observable<Token> {
    return null;
  }
```

**Comment by hboylan** [comment]
I'm currently working on [this solution](https://github.com/hboylan/ng2-http/issues/11#issuecomment-280786562). Thanks for your input.

**Comment by daibertdiego** [comment]
@iagocanalejas the token that i need refresh before any request is the CSRF-TOKEN and this can't be refreshed only if a unauthorized exception occurs for security reasons. The user authentication token that going with the CSRF-TOKEN on header is OK.

@hboylan do you have some prevision about this feature?

Thankyou

**Comment by iagocanalejas** [comment]
@daibertdiego sorry i completely misunderstood your question and mess up a bit :(

**Comment by hboylan** [comment]
Tried working on this again today. Still having trouble implementing the solution mentioned above. Can't seem to correctly return the ```Observable<Response>``` after wrapping the request interceptor in an Observable.

Trying to update [util.ts](https://github.com/hboylan/ng2-http/blob/master/src/util.ts#L113):
```typescript
// intercept the request
return this.requestInterceptor(opts).map((req: Request): Observable<Response> => {

  // make the request and store the observable for later transformation
  var observable: Observable<Response> = this.http.request(req);

  // global response interceptor
  observable = this.responseInterceptor(observable);

  // transform the obserable in accordance to the @Produces decorator
  if (descriptor.producer) {
    observable = observable.map(descriptor.producer);
  }

  return observable;
})
```

**Comment by hboylan** [comment]
Any suggestions [here](https://github.com/hboylan/ng2-http/blob/99f5edd5d1ef09a2bb0de0245286a06e314ea6dc/src/util.ts#L115)?
