### ISSUE TITLE
Cannot POST multipart/form-data

### ISSUE THREAD

**Issue by ernest-rhinozeros** [hboylan/ng2-http#16]
It is not possible to send multipart/form-data POST requests (using a `<input type="file">`) because of this code snippet:
```
if (urlencoded && urlencoded === 'application/x-www-form-urlencoded') {
  body = args[pBody[0].parameterIndex];
} else {
  body = JSON.stringify(args[pBody[0].parameterIndex]);
}
```
If you want to send multipart requests the browser will handle the headers (set them to `multipart/form-data;boundary=...`), so the `Content-Type` header has to be empty.

If you have an `<input #file type="file" (change)="upload(file)">` you can create a POST request like this:
```
upload(input: HTMLInputElement) {
  let file: FileList = input.files[0];
  let formData: FormData = new FormData();
  formData.append('file', file, file.name);
  this.http.post(url, formData, { headers: new Headers() });
}
```

**Comment by hboylan** [comment]
@ernest-rhinozeros `ng2-http` was originally intended for use with JSON REST APIs, but I'm happy to see that you'd like to use it to upload multipart data.

1. Are you familiar with the source code?
2. Do you have any suggestions for a solution?
3. Perhaps an `@Mutlipart` or `@Upload` decorator?

**Comment by b264** [comment]
Should this be a 1.1.0 milestone?

**Comment by xTaz1** [comment]
I will try tomorrow create `@Upload `decorator

**Comment by hboylan** [comment]
v1.0.1
