### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by Wolfium** [hboylan/ng2-http#19]
I used example from readme (installed cli and then a generator) and always get asked about the package name to use, even if I pass the parameters to init (ie: generator and mode) `swagen init --generator ng1-http --mode typescript`

If package is installed question is asked again indefinitely.
 
Even I tried several different cliente, ng1-http, ng2-http, dotnet-httpclient all same issues.

Finally looking in source code if I pass `--defaults` I get a mode property not defined error.

```javascript
C:\Users\nlobo\AppData\Roaming\npm\node_modules\swagen\lib\init\index.js:75
        mode: mode.name,
                  ^

TypeError: Cannot read property 'name' of undefined
    at buildConfig (C:\Users\nlobo\AppData\Roaming\npm\node_modules\swagen\lib\init\index.js:75:19)
    at module.exports (C:\Users\nlobo\AppData\Roaming\npm\node_modules\swagen\lib\init\index.js:109:9)
    at Object.<anonymous> (C:\Users\nlobo\AppData\Roaming\npm\node_modules\swagen\cli.js:32:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

Any idea of that I would be doing wrong.

**Comment by b264** [comment]
Are you using Angular 2, 3, or 4? Or Angular 1.x?

**Comment by hboylan** [comment]
@Wolfium Looks like you're using the [swagen](https://www.npmjs.com/package/swagen) npm package.

Not sure what `swagen init --generator ng1-http --mode typescript` is supposed to do, but you should be installing this library with either `yarn add ng2-http` or `npm i ng2-http`

**Comment by Wolfium** [comment]
Correct, that was the intent, but when failing tried with other to check workflow and no one worked, even I could see that it is supposed to use swagen-angular instead of ng2-http.

Just installed swagen (cli) and swagen-ng2-http and it didn't work, versions got them from yarn add below...

```json
{
  "name": "swagen-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "swagen": "0.0.45",
    "swagen-angular": "^0.0.9",
    "swagen-dotnet-httpclient": "^0.0.14",
    "swagen-ng1-http": "0.0.54",
    "swagen-ng2-http": "0.0.7"
  }
}
```

Any help would be really apprecitated

**Comment by Wolfium** [comment]
Re opening, closed by mistake...

**Comment by hboylan** [comment]
@Wolfium I'm not familiar with swagen, but the NPM package [swagen-ng2-http](https://www.npmjs.com/package/swagen-ng2-http) appears to be an Angular HTTP generator for it. This is an entirely separate library from [ng2-http](https://www.npmjs.com/package/ng2-http).
