### ISSUE TITLE
Why not return interceptor in @Produces ?

### ISSUE THREAD

**Issue by akarabach** [hboylan/ng2-http#20]
Originally, I thought that we need interceptor in `@Produces` for creating custom producer. For example: 
my server return data like this: 
```
{
  "data": {
    "original": "a",
    "original2": "b"
  }
}
```
and I have to create interceptor like this :
```
@GET(route)
@Produces<MockModel>(r => r.json().data as MockModel)
```
My MockModel
```
export class MockModel {
  constructor (original:string, original2:string){}
}
```
But then I looked in [rest.service.ts](https://github.com/hboylan/ng2-http/blob/master/src/rest.service.ts)

```
export function Produces<T>(interceptor?: (res: Response) => void) {
  return function(target: RESTClient, propertyKey: string, descriptor: any) {
    descriptor.producer = (res: Response) => {
      if (interceptor) {
        interceptor(res)
      }
      return <T>res.json()
    }
    return descriptor;
  };
}

```

Why we need interceptor? Or you missed `return `? (`return interceptor(res)`)

**Comment by hboylan** [comment]
@xTaz1 Good catch! 💯
