### ISSUE TITLE
@Query for object

### ISSUE THREAD

**Issue by akarabach** [hboylan/ng2-http#27]
```
//some my rest service
 @GET(someRoute)
 @Produces<any>()
  getSomething(@Query('object') queries: SomeObject): Observable<any> {
    return null;
  }
```
So, when I send to my rest service object and when I added **`@Query('object')`** (with **object** key), I want to see request with all my properties from object that I send to method.

It's really helpful when you have request with many query params and when you want build query in loop (for the example)

In this implementation object transform like this: JSON.stringify(value), but I don't understand why this is necessary? Please describe your position or approve my pull request.

**Comment by hboylan** [comment]
Was a temporary way to pass objects until someone came along and made this change.

I'm traveling today but will push this to npm ASAP

**Comment by hboylan** [comment]
Actually, the ability to pass in a class like `@Query(SomeClass)` would be even better. Using `@Query('object')` has just created a reserved word for query parameters that may require the name "object".

Perhaps we should implement a class `QueryObject`? It could even automatically map to a string and allow that method to be overriden.

**Comment by akarabach** [comment]
@hboylan I thought about it. But, I had use this feature `@Query('object')` about 3 weeks and I didn't have any problems.

**Comment by hboylan** [comment]
Cannot find time to work on this repo atm. Would you like to collaborate to maintain?

**Comment by hboylan** [comment]
v1.0.1
