### ISSUE TITLE
Query params as an object

### ISSUE THREAD

**Issue by DanielKucal** [hboylan/ng2-http#29]
Consider the following http endpoint:
```
    @GET('users/{userId}/posts')
    public getPosts(@Path('userId') userId: string,
                             @Query('from') from: string,
                             @Query('to') to: string,
                             @Query('status_id') statusId?: number,
                             @Query('label_id') labelId?: number,
                             @Query('account_id') accountId?: string,
                             @Query('limit') limit: number = 500,
                             @Query('order') order: 'asc' | 'desc' = 'asc',
    ): EndPoint<{posts: Array<Post>}> {
        return undefined;
    }
```
As you can see, it can contain many query parameters. If I'd like to set just the `limit`, my code will look this way:
```
getModulePosts('1', undefined, undefined, undefined, undefined, undefined, 2000);
```
... what is kind of weird for me. And there is also a second problem here: the default values for `limit` and `order` parameters are not set. So here comes my question: can I make it better? Would be great to have something like `@Body` decorator, but for query params, so I could just pass simple object `{ limit: 2000 }` in this case... Thanks in advance.

**Comment by b264** [comment]
I made my {"own": "class", "that": "turns"} ?objects=into&query=parameters

so for example
``` typescript
  @GET('/items/{query}')
  @Produces<Item[]>()
  public index(@Path('query') query?: string): Observable<Item[]> {
    return null;
  };
```

``` typescript
export class Query {
  public bits: QueryBit[] = [];
  constructor() {}
  public toString(): string {
    return '?' + this.bits.map((object, index, array) => {
      for(let propertyName in object) {
        if (object[propertyName] != undefined && object[propertyName] != null)
          return propertyName + '=' + object[propertyName];
      }
    }).join('&');
  }
}
interface QueryBit {                    // app-wide whitelisted query parameters
  limit?: number,
  offset?: number,
  type?: string,
}
```
``` typescript
export class Thing extends OtherThing {
  private query: Query = new Query;
  constructor(private itemService: ItemService) {}
  public listItems(type: string, limit: number): void {
    this.query.bits = [
      {'limit': limit},
      {'type': this.type},
    ];
    this.itemService.index(this.query.toString()).subscribe(/* your code */);
  };
};
```

See the `this.query.toString()` part?  That solves your problem.  This should probably be a library itself or part of this library.

**Comment by DanielKucal** [comment]
Thanks... However, I've seen that it was probably already merged in #28, but new npm package still hasn't been published.
PS: expressions like `new Query;` without `()` can be not passed by Angular compiler.

**Comment by hboylan** [comment]
I hesitated to publish the fix pending a [discussion](https://github.com/hboylan/ng2-http/issues/27#issuecomment-331160434) over issue #27.

**Comment by akarabach** [comment]
@DanielKucal  `@Query('order') order: 'asc' | 'desc' = 'asc'`. Default members doesn't work. You can create issue for this.

**Comment by hboylan** [comment]
v1.0.1
