### ISSUE TITLE
Default values don't work

### ISSUE THREAD

**Issue by DanielKucal** [hboylan/ng2-http#34]
Consider API method defined this way:
```
@GET('some/resource/{id}')
getSomething(
  @Path('id') id: number = 0,
  @Query('limit') limit: number = 15,
): Observable<Something> {
  return undefined;
}
```
Default values for `id` and `limit` parameters are ignored...

**Comment by xTaz1** [comment]
duplicated https://github.com/hboylan/ng2-http/issues/32

**Comment by akarabach** [comment]
duplicated https://github.com/hboylan/ng2-http/issues/32
