### ISSUE TITLE
Empty package on npm?

### ISSUE THREAD

**Issue by DanielKucal** [hboylan/ng2-http#36]
When I installed `ng2-http@latest` (v1.0.1) empty package has came:
![image](https://user-images.githubusercontent.com/8938562/35483143-ef7ed0b2-043e-11e8-9127-1afa676f1fa2.png)
The `dist` directory is empty, so I get errors like:
> TS2307: Cannot find module 'ng2-http'.

Tried it twice, package for v1.0.0 is fine.

**Comment by hboylan** [comment]
Must've run `npm publish` after already cleaning the dist directory, my bad.

`npm i ng2-http@1.0.2`
