### ISSUE TITLE
redundant encodeURIComponent

### ISSUE THREAD

**Issue by nelsonec87** [hboylan/ng2-http#5]
Hi, I'm playing with your lib (super cool) and I tried to send a Query parameter using 

`@Query("$size")
`
It means the page size in APISpark.
It was not working... I checked the network tab in Chrome and the lib was sending `"%2524size"` which is `"$size"` URLEncoded twice.

I removed `encodeURIComponent `from util.js

`search.set(encodeURIComponent(key), encodeURIComponent(value));`

and it worked.

I put other special characters to test and it encoded them automatically.

**Comment by hboylan** [comment]
Hey, good find!

Looks like the URLSearchParams class from @angular/http now encodes them for us. We'll definitely get this fixed and tested ASAP.

**Comment by nelsonec87** [comment]
Thanks for the really quick response!
I know it is not the place, but i dont wanna open another issue without knowing if it is your module's problem or some CORS config... A cannot access custom headers from the response. (X-Page-Count, etc)

I get 
![image](https://cloud.githubusercontent.com/assets/3801502/20938030/85a20f36-bbd0-11e6-8e7f-360157c6cfa3.png)
in the network inspector, but in the console the headers' size is 1:

![image](https://cloud.githubusercontent.com/assets/3801502/20938010/728f7122-bbd0-11e6-908f-cf9e754a5729.png)

**Comment by hboylan** [comment]
Fixed this issue with v0.0.3

I can confirm that only certain headers show up for some reason. It's pulling the @angular/http [Headers](https://fetch.spec.whatwg.org/#headers-class) from Response so that's a better place to research the problem.

I'd be interested to know the reason if you find out.

**Comment by nelsonec87** [comment]
Updated to 0.0.3, thanks.

The header issue is related to CORS... when I run the interface from the same host:port it works as it should.
In cross domain requests, the **server** must white-list the headers the browser can access:

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Expose-Headers)
