### ISSUE TITLE
Error Handler

### ISSUE THREAD

**Issue by khatv911** [hboylan/ng2-http#6]
Please guide us how to add handler for  Http or self-defined error? Thanks

**Comment by hboylan** [comment]
Sure, you'd just use the response interceptor in the service that extends RESTClient to intercept errors.

Angular2 HTTP calls use [Observables](http://stackoverflow.com/questions/35326689/how-to-catch-exception-correctly-from-http-request) so you can just ```.catch()``` them.

```typescript
protected responseInterceptor(res: Observable<Response>): Observable<Response> {
    return res
}
```
