### ISSUE TITLE
Dynamic Headers Help

### ISSUE THREAD

**Issue by Schwoebel** [hboylan/ng2-http#7]
Hi @hboylan !  I really like the app you have done here.  I was curious about something.  I can't seem to add a Header to a call if I need to include a variable.
Something like :
```
    @GET('/user')
    @Produces<User>()
    @Headers({
        'Authorization' : 'Bearer ' + this.getToken()
    })
    public getUser(): Observable<User> {
        return
    }
```
I understand that you can't do it the way I have written above, but I was wondering if you could help me since you have a much better understanding of Typescript than I do.

**Comment by hboylan** [comment]
What you have here is a static header example. You can do this on a service that implements ```RESTClient``` like this:

```typescript
@BaseUrl('https://jsonplaceholder.typicode.com')
@DefaultHeaders({
  'Accept': 'application/json',
  'Content-Type': 'application/json'
})
export class DemoService extends RESTClient {}
```

This method doesn't work for dynamic headers that change at runtime. Instead, you would use an HTTP interceptor within your service like this:

```typescript
protected requestInterceptor(req: Request): Request {
  let user = this.localStorage.get<User>('user')
  if (user && user.token) {
    req.headers.set('Authorization', `Bearer ${user.token}`)
  }
  return req
}

protected responseInterceptor(res: Observable<Response>): Observable<Response> {
  return res.map((res) => {
    if (res.url.indexOf('/user/login') !== -1 && res.ok) {
      this.localStorage.set('user', res.json())
    }
    return res
  }).catch((error) => {
    this.router.navigate(['login'])
    return Observable.throw(error)
  })
}
```

**Comment by Schwoebel** [comment]
I wanted to say thanks for your help.
