### ISSUE TITLE
How to add more than one @Query

### ISSUE THREAD

**Issue by b264** [hboylan/ng2-http#9]
What if instead of

`POST http://example.com?a=1`
I need
`POST http://example.com?a=1&b=2`

Is this possible with this library?

**Comment by hboylan** [comment]
Hmm. Haven't tested it myself, but you should be able to add multiple params just like any other function. Give it a try.

```typescript
@GET('/')
@Produces<Example>()
public getExample(@Query('a') a?: number, @Query('b') b?: number): Observable<Example> {
  return null;
}
```

**Comment by b264** [comment]
That code seems to work, but it only ever sends the first query parameter over http. `a` in this case

**Comment by b264** [comment]
This does seem to work... Apparently if you send `undefined` as the value it does not write `?a=1&b=` but instead writes `?a=1` which is a slightly different thing
